BEGIN;

-- Suppression des tables existantes
DROP TABLE IF EXISTS "user_has_follow";
DROP TABLE IF EXISTS "skill_has_review";
DROP TABLE IF EXISTS "user_has_skill";
DROP TABLE IF EXISTS "notification";
DROP TABLE IF EXISTS "message";
DROP TABLE IF EXISTS "review";
DROP TABLE IF EXISTS "skill";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "role";

-- Création des tables sans les clés étrangères
CREATE TABLE "role"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "label" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "bio" TEXT,
    "image" TEXT,
    "interest" TEXT,
    "is_available" BOOLEAN DEFAULT false,
    "role_id" INT NOT NULL REFERENCES "role"("id") DEFAULT 1,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "skill"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "label" TEXT NOT NULL UNIQUE,
    "slug" TEXT NOT NULL UNIQUE,
    "icon" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "review"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "rate" INT NOT NULL CHECK ("rate" >= 1 AND "rate" <= 5),
    "content" TEXT,
    "reviewer_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "reviewed_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "skill_id" INT NOT NULL REFERENCES "skill"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    UNIQUE("reviewer_id", "reviewed_id", "skill_id")
);

CREATE TABLE "message"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "content" TEXT NOT NULL,
    "sender_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "receiver_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "is_read" BOOLEAN DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "notification"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type_notification" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "is_read" BOOLEAN NOT NULL DEFAULT false,
    "related_entity_type" TEXT,
    "related_entity_id" INT,
    "action_url" TEXT,
    "user_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user_has_skill"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "skill_id" INT NOT NULL REFERENCES "skill"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    UNIQUE("user_id", "skill_id")
);

CREATE TABLE "user_has_follow"(
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "follower_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "followed_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ,
    UNIQUE("follower_id", "followed_id")
);

-- Index sur les FK fréquemment utilisées dans les jointures/WHERE
-- (les colonnes UNIQUE et PK ont déjà un index automatique)
CREATE INDEX idx_review_reviewer_id ON "review"("reviewer_id");
CREATE INDEX idx_review_reviewed_id ON "review"("reviewed_id");
CREATE INDEX idx_message_sender_id ON "message"("sender_id");
CREATE INDEX idx_message_receiver_id ON "message"("receiver_id");
CREATE INDEX idx_notification_user_id ON "notification"("user_id");

COMMIT;
