-- Migration V3 : messagerie temps reel + recherche avancee
-- A executer sur une base existante (production)

BEGIN;

-- securiser les colonnes notifications (si v2 n'a pas ete jouee)
ALTER TABLE "notification"
  ADD COLUMN IF NOT EXISTS "is_read" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "related_entity_type" TEXT,
  ADD COLUMN IF NOT EXISTS "related_entity_id" INT,
  ADD COLUMN IF NOT EXISTS "action_url" TEXT;

-- message.read_at pour timestamp de lecture
ALTER TABLE "message"
  ADD COLUMN IF NOT EXISTS "read_at" TIMESTAMPTZ;

-- user.city pour filtre de recherche
ALTER TABLE "user"
  ADD COLUMN IF NOT EXISTS "city" TEXT;

-- table des recherches sauvegardees
CREATE TABLE IF NOT EXISTS "saved_search"(
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "filters" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_saved_search_user_id ON "saved_search"("user_id");

COMMIT;
